name: Test Project Lab 2
on:
  push:
    branches:
      - main

jobs:
  run-on-merge:
    runs-on: ubuntu-latest

    steps:
      - name: pull code
        uses: actions/checkout@v6
      - name: set python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.11"
      - name: install dep
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        working-directory: "./GH_Actions/lab2"
      - name: run it
        run: |
          python -m pytest test_string_utils.py
        working-directory: "./GH_Actions/lab2"
      - name: Done lab2
        run: echo "deploying application"
