name: Test Project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull code
        uses: actions/checkout@v6
      - name: set python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.11'
      - name: install dep
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        working-directory: './GH_Actions/lab1'
      - name: run tests
        run: |
         pytest
        working-directory: './GH_Actions/lab1'
      - name: Done lab2
        run: echo "Lab 2 completed"
        
           